<div class="hero-unit">
   	<?php if(count($paramsOrder["allCart"]) > 0): ?>
    <p class="text-header">
    	<span class="titFel">¡FELICIDADES!</span> has finalizado tu canje con &eacute;xito.
    </p>
    <p class="text-sub">
    	Tu n&uacute;mero de folio es <span class="textFolio"><?php echo $paramsOrder['order']; ?></span>. <br />
    	Gu&aacute;rdalo o <a href="#" onclick="javascript:window.print();" id="link-print">impr&iacute;melo</a> para cualquier duda y/o aclaraci&oacute;n.
    </p>
    <p class="text-sub">
    	<h5>Detalle del canje</h5>
    	<div class="table_tl order-detail">
    		<h5>Fecha: <?php echo $paramsOrder['date'] ?></h5>
            <h5>Nombre: <?php echo $paramsOrder['usename'] ?></h5>
    		<pre>
    			<?php // var_dump(count($paramsOrder["allCart"])) ?>
    		</pre>
    		<table>
				<tr>
					<td width="16%">&nbsp;</td>
					<td width="16%">Imagen</td>
					<td width="16%">Producto</td>
					<td width="16%">Categor&iacute;a</td>
					<td width="16%">Cantidad</td>
					<td width="16%">Precio</td>
				</tr>
				<?php $i=0; foreach ($this->paramsOrder['allCart'] as $item): $i++; ?>
					<tr>
						<td><?php echo $i ?></td>
	                    <td><img src="<?php echo $this->basePath('img/product/' . $item['thumb_image']) ?>" /></td>
	                    <td><?php echo $item['sku'] . " " . $item['other_sku'] ?></td>
	                    <td><?php echo $item['category'] ?></td>
	                    <td><?php echo $item['quantity'] ?></td>
	                    <td><?php echo number_format(((float) $item['price']), 0, '.', ',') ?></td>
	                </tr>
				<?php endforeach; ?>

				
			</table>
    	</div>
    </p>
    <?php else: ?>
    <h4>Tu carrito de canje est&aacute; vac&iacute;o.</h4>
    <h5><href="#" class="link-check">Regresa al cat&aacute;logo</a>.</h5>
    <?php endif ?>

</div>