<div class="notification notification--info">alert</div>
<div class="hero-unit">
	<p class="text-header">
    	<span class="titFel">Administrar cuotas a <?php echo $participante->fullname ?></span><br/> 
    		Aquí puedes editar las cuotas de por mes. Haz clic en la cantidad de cuota para editar.
    </p>
    <div class="content app_content">
    	<div class="clearfix" style="margin-bottom: 40px;"></div>
    	
    		<p>
    			<strong>Vendedor:</strong> <?php echo $participante->fullname ?>
    		</p>
    		<p>
    			<strong>Sucursal:</strong> <?php echo $sucursal ?>
    		</p>
    		<p>
    			<strong>Nombre de usuario:</strong> <?php echo $participante->username ?>
    		</p>

	        <h1>Cuotas Familias
                <a href="<?php echo $this->url('cuotas') ?>" class="btn btn--tertiary btn-right">Regresar</a>
            </h1>
            <table class="dataTable adminTable">
                <thead>
                    <th>#</th>
                    <th>Familia</th>
                    <th>Mes</th>
                    <th>Cuota</th>
                    <th class="tright">&nbsp;</th>
                </thead>
                <tbody>
                <?php $i=0; foreach ($cuotas_f as $cuota_f) { $i++ ?>

                    <tr id="cuota_<?php echo $cuota_f["cuota_id"] ?>"  class="<?php echo strtolower($meses_txt[$cuota_f["mes"]]) ?>"
                            data-user="<?php echo $cuota_f["usuario_id"] ?>" 
                                data-cta="<?php echo $cuota_f["cuota_id"] ?>">
                        <td><?php $i ?></td>
                        <td><?php echo $cuota_f["familia"] ?></td>
                        <td><?php echo $meses_txt[$cuota_f["mes"]] ?></td>
                        <td class="cell_cuota">
                            <input type="text" class="invisible-border" title="Clic para editar cuota" 
                                value="<?php echo $cuota_f["cuota"] ?>" id="cell_cuota_<?php echo $cuota_f["cuota_id"] ?>"
                                    onkeypress="return isNumberKey(event)"  />
                        </td>
                        <td><a href="#" class="btn-admin btn--positive btn-cuota" data-btn="<?php echo $cuota_f["cuota_id"] ?>"
                                data-reference="familias" >Guardar</a></td>
                    </tr>

                <?php } ?>
                </tbody>
            </table>

            <h1>Cuotas Aplicaciones
                <a href="<?php echo $this->url('cuotas') ?>" class="btn btn--tertiary btn-right">Regresar</a>
            </h1>
            <table class="dataTable adminTable">
                <thead>
                    <th>#</th>
                    <th>Familia</th>
                    <th>Mes</th>
                    <th>Cuota</th>
                    <th class="tright">&nbsp;</th>
                </thead>
                <tbody>
                <?php $i=0; foreach ($cuotas_a as $cuota_a) { $i++ ?>

                    <tr id="cuota_<?php echo $cuota_a["cuota_id"] ?>"  class="<?php echo strtolower($meses_txt[$cuota_a["mes"]]) ?>"
                            data-user="<?php echo $cuota_a["usuario_id"] ?>" 
                                data-cta="<?php echo $cuota_a["cuota_id"] ?>">
                        <td><?php $i ?></td>
                        <td><?php echo $cuota_a["familia"] ?></td>
                        <td><?php echo $meses_txt[$cuota_a["mes"]] ?></td>
                        <td class="cell_cuota">
                            <input type="text" class="invisible-border" title="Clic para editar cuota" 
                                value="<?php echo $cuota_a["cuota"] ?>" id="cell_cuota_<?php echo $cuota_a["cuota_id"] ?>"
                                    onkeypress="return isNumberKey(event)"  />
                        </td>
                        <td><a href="#" class="btn-admin btn--positive btn-cuota" data-btn="<?php echo $cuota_a["cuota_id"] ?>"
                                data-reference="aplicaciones" >Guardar</a></td>
                    </tr>

                <?php } ?>
                </tbody>
            </table>
    </div>

</div>
<script type="text/javascript">
    function isNumberKey(event){
        var charCode = (event.which) ? event.which : event.keyCode
         if (charCode != 46 && charCode > 31 && (charCode < 48 || charCode > 57))
            return false;

         return true;
    }
</script>