<div class="hero-unit">
	<p class="text-header">
    	<span class="titFel">Editar participante</span><br/> 
    		Edita la informaci&oacute;n del participante en el sistema.
    </p>
    <div style="margin-bottom: 40px;"></div>
    <div class="content app_content">
		<?php
		$form->prepare();
		$form->setAttribute('action', $this->basePath('admin-usuarios/editar-participante'));
		$form->setAttribute('method', 'post');
		$form->setAttribute('class', 'reg-form complete-form')
		?>
		<?php echo $this->form()->openTag($form) ?>
			<h1><?php echo  $participante ?></h1>
			<?php if(count($form->getMessages())): ?>
				<div class="alert-error">Ha ocurrido un error. Por favor verifique sus datos.</div>
			<?php endif ?>
		    <div class="form-group">
		    	<?php echo $this->formHidden($form->get('user_id')); ?>
		    	<?php echo $this->formHidden($form->get('status')); ?>
		        <?php echo $this->formRow($form->get('fullname')) ?>
		    </div>
			<div class="form-group">
		        <?php echo $this->formRow($form->get('phone')) ?>
		    </div>
		    <div class="form-group">
		        <?php echo $this->formRow($form->get('cellphone')) ?>
		    </div>
		    <div class="form-group">
		        <?php echo $this->formRow($form->get('email')) ?>
		    </div>
		    <div class="form-group">
		        <?php echo $this->formRow($form->get('birthdate')) ?>
		    </div>
		    <div class="form-group">
		        <?php echo $this->formRow($form->get('domicilio')) ?>
		    </div>
		    <div class="form-group">
		        <?php echo $this->formRow($form->get('municipio')) ?>
		    </div>
		    <div class="form-group">
		        <?php echo $this->formRow($form->get('estado')) ?>
		    </div>
		    <div class="form-group">
		        <?php echo $this->formRow($form->get('zipcode')) ?>
		    </div>
		    <div class="form-group">
		        <?php echo $this->formRow($form->get('perfil')) ?>
		    </div>
		    <div id="parent_content" class="form-group">
		        <?php echo $this->formRow($form->get('parent')) ?>
		    </div>
		    <div id="sucursal_content" class="form-group">
		        <?php echo $this->formRow($form->get('sucursal')) ?>
		    </div>
		    
			<div class="form-group">
		    	<a href="<?php echo $this->basePath('admin-participantes') ?>" class="btn-admin btn--secondary">Cancelar</a>
		    	<input type="submit" class="btn-admin btn--positive" value="Guardar participante" />
		    </div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>