<?php 
	$url = $this->url('participantes', array(
		'action' => 'eliminar-participante',
		'id'     => $participante_id,
	))
?>
<div class="hero-unit">
	<p class="text-header">
    	<span class="titFel">Eliminar participante</span><br/> 
    </p>
    <div class="content app_content">
    	<h2>Nombre: <?php echo $this->escapeHtml($participante->fullname) ?></h2>
    	<form action="<?php echo $url; ?>" method="post">
			<div>
				<input type="hidden" name="id" value="<?php echo (int) $participante->user_id; ?>" />
			 	<input type="submit" name="del" value="Eliminar" class="btn-admin btn--secondary" />
			 	<input type="submit" name="del" value="Cancelar" class="btn-admin btn--positive" />
			</div>
		</form>

    </div>
</div>