<div class="alert-msg" style="<?php echo $hidden ?>"><span>Los datos han sido procesados con éxito.</span></div>

<div class="hero-unit">
	<p class="text-header">
    	<span class="titFel">Editar sucursal</span><br/> 
    		Edita el nombre y el distribuidor para la sucursal
    </p>
    <div class="content app_content">
		<?php
		$form->prepare();
		$form->setAttribute('action', $this->basePath('admin-sucursales/editar-sucursal'));
		$form->setAttribute('method', 'post');
		$form->setAttribute('class', 'reg-form complete-form')
		?>
		<?php echo $this->form()->openTag($form) ?>
		    <h1><?php echo  $sucursal ?></h1>

			<?php if(count($form->getMessages())): ?>
				<div class="alert-error">Ha ocurrido un error. Por favor verifique sus datos.</div>
			<?php endif ?>
		    <div class="form-group">
		    	<?php echo $this->formHidden($form->get('sucursal_id')); ?>
		        <?php echo $this->formRow($form->get('nombre')) ?>
		    </div>
			<div class="form-group">
		        <?php echo $this->formRow($form->get('distribuidor')) ?>
		    </div>
		    
			<div class="form-group">
		    	<a href="<?php echo $this->basePath('admin-sucursales') ?>" class="btn-admin btn--secondary">Cancelar</a>
		    	<input type="submit" class="btn-admin btn--positive" value="Guardar sucursal" />
		    </div>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>