<?php
$title = $this->escapeHtml($collection->name);
$this->headTitle($title);

$base_url = substr($this->serverUrl($this->url('home')), 0, -8);
?>
<?php echo "<br />"; ?>
<div class="collections-view view-container">
	
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="fa fa-book fa-lg"></i> <?= $title; ?>
		</div>
		<div class="panel-body">
			
			<div class="row">
				<div class="col-md-6">
					<h3>Productos en ésta colección</h3>
					<table class="table table-hover">
						<thead>
						    <tr>
						        <th>#</th>
						        <th>&nbsp;</th>
						        <th>Código</th>
						        <th>Nombre</th>
						        <th>Categoría</th>
						        <th>&nbsp;</th>
						    </tr>
						</thead>
						<tbody>
							<?php foreach($in_products as $in_product){ $i++; ?>
								<tr>
									<td valign="middle"><?= $this->escapeHtml($i); ?></td>
				        			<td>
				        				<img src="<?= $base_url.$this->escapeHtml($in_product->product_thumbnail); ?>" width="50" height="50" />
				        			</td>
				        			<td valign="middle"><?= $in_product->product_code; ?></td>
				        			<td valign="middle"><?= $this->escapeHtml($in_product->product_name); ?></td>
				        			<td valign="middle">
				        				<span class="label label-success"><?= $this->escapeHtml($in_product->category_name); ?></span>
				        			</td>
				        			<td>
				        				<?php 
				        					$action_url = $this->url(
				        						'collections', array('action'=>'remove-from-collection')
				        					);
				        				?>
										<form action="<?= $action_url; ?>" method="post">
				        					<input type="hidden" name="remove_row" value="<?= $in_product->id; ?>" />
								            <button type="submit" title="Eliminar de la colección" data-toggle="tooltip" data-placement="top" class="action_event link_tooltip">
								            	<span class="glyphicon glyphicon-ban-circle"></span>
								            </button>
								        </form>
							        </td>
								</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
				<div class="col-md-6">
					<h3>Agregar otros productos</h3>
					<?php $url = $this->url('collections', array('controller' => 'collections', 'action' => 'search-result')); ?>
					<form action="<?php echo $url; ?>" method="post" class="navbar-form navbar-right" id="search-product" role="search" >
						<div class="form-group">
							<input type="text" name="search-filter" id="search-code" class="form-control" placeholder="Código" />
							<input type="hidden" name="search-collection" id="search-collection" class="form-control" value="<?= $collection->id; ?>" />
						</div>
						<button type="submit" class="btn btn-info"><span class="glyphicon glyphicon-search"></span> Buscar</button>
						<!-- <a href="#" class="btn btn-info"><span class="glyphicon glyphicon-cog"></span> Búsqueda avanzada</a> -->
					</form>
					<table id="to-add-products-table" class="table table-hover">
						<thead>
						    <tr>
						        <th>#</th>
						        <th>&nbsp;</th>
						        <th>Código</th>
						        <th>Nombre</th>
						        <th>Categoría</th>
						        <th>&nbsp;</th>
						    </tr>
						</thead>
						<tbody>
							<?php foreach($products as $product){ $i++; ?>
								<tr>
									<td valign="middle"><?= $this->escapeHtml($i); ?></td>
				        			<td>
				        				<img src="<?= $base_url.$this->escapeHtml($product->thumbnail); ?>" width="50" height="50" />
				        			</td>
				        			<td valign="middle"><?= $product->code; ?></td>
				        			<td valign="middle"><?= $this->escapeHtml($product->name); ?></td>
				        			<td valign="middle">
				        				<span class="label label-success"><?= $this->escapeHtml($product->category_name); ?></span>
				        			</td>
				        			<td>
				        				<?php 
				        					$action_url = $this->url(
				        						'collections', array('action'=>'add-to-collection')
				        					);
				        				?>
				        				<form action="<?= $action_url; ?>" method="post">
				        					<input type="hidden" name="collection" value="<?= $collection->id; ?>" />
				        					<input type="hidden" name="product" value="<?= $product->id; ?>" />
								            <button type="submit" title="Agregar a la colección" data-toggle="tooltip" data-placement="top" class="action_event link_tooltip">
								            	<span class="glyphicon glyphicon-plus"></span>
								            </button>
								        </form>
							        </td>
								</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
			</div>

		</div>
	</div>
	

</div>