<?php
$title = 'Editar Colección';
$this->headTitle($title);
echo "<br />";
?>
<div class="collections-view view-container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<i class="fa fa-book fa-lg"></i> <?= $title; ?>
		</div>
		<div class="panel-body">
			<?php
				$form->setAttribute('collections', $this->url('collections', array('action' => 'edit','id' => $this->id,)));
				$form->setAttribute('class', 'form-horizontal');
				$form->prepare();

				echo $this->form()->openTag($form);
			?>
			<div class="row">
				<div class="col-md-6">
					<?php
						echo $this->formHidden($form->get('id'));
						echo $this->formRow($form->get('name'));
					?>
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="button-set">
				<a href="<?= $this->url('collections', array('action'=>'index')); ?>" class="btn btn-danger">
					<span class="glyphicon glyphicon-remove"></span> Cancelar</a>
				</a>
				<button type="submit" id="btn-save" name="submit" class="btn btn-success">
					<span class="glyphicon glyphicon-floppy-disk"></span> Guardar Colección
				</button>
			</div>

			<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>
</div>