<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Category implements CategoryInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var int              
     */
      protected $idparent;  

    /**
     * @var varchar              
     */
      protected $name;  

    /**
     * @var text              
     */
      protected $description;  

    /**
     * @var varchar              
     */
      protected $thumbimg;  

    /**
     * @var varchar              
     */
      protected $fullimg;  

    /**
     * @var int              
     */
      protected $lastupdate;  

    /**
     * @var int              
     */
      protected $categoryorder;  

    /**
     * @var int              
     */
      protected $categorystatus;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set idparent
     *
     * @param int $idparent
     * @return type                   
     */            
	public function setIdparent($idparent){
		$this->idparent = (int) $idparent;
	}
    /**
     * Get idparent
     *
     * @return int
     */          
	public function getIdparent(){
		return $this->idparent;
	}
    /**
     * Set name
     *
     * @param varchar $name
     * @return type                   
     */            
	public function setName($name){
		$this->name = (string) $name;
	}
    /**
     * Get name
     *
     * @return varchar
     */          
	public function getName(){
		return $this->name;
	}
    /**
     * Set description
     *
     * @param text $description
     * @return type                   
     */            
	public function setDescription($description){
		$this->description = (string) $description;
	}
    /**
     * Get description
     *
     * @return text
     */          
	public function getDescription(){
		return $this->description;
	}
    /**
     * Set thumbimg
     *
     * @param varchar $thumbimg
     * @return type                   
     */            
	public function setThumbimg($thumbimg){
		$this->thumbimg = (string) $thumbimg;
	}
    /**
     * Get thumbimg
     *
     * @return varchar
     */          
	public function getThumbimg(){
		return $this->thumbimg;
	}
    /**
     * Set fullimg
     *
     * @param varchar $fullimg
     * @return type                   
     */            
	public function setFullimg($fullimg){
		$this->fullimg = (string) $fullimg;
	}
    /**
     * Get fullimg
     *
     * @return varchar
     */          
	public function getFullimg(){
		return $this->fullimg;
	}
    /**
     * Set lastupdate
     *
     * @param int $lastupdate
     * @return type                   
     */            
	public function setLastupdate($lastupdate){
		$this->lastupdate = (int) $lastupdate;
	}
    /**
     * Get lastupdate
     *
     * @return int
     */          
	public function getLastupdate(){
		return $this->lastupdate;
	}
    /**
     * Set categoryorder
     *
     * @param int $categoryorder
     * @return type                   
     */            
	public function setCategoryorder($categoryorder){
		$this->categoryorder = (int) $categoryorder;
	}
    /**
     * Get categoryorder
     *
     * @return int
     */          
	public function getCategoryorder(){
		return $this->categoryorder;
	}
    /**
     * Set categorystatus
     *
     * @param int $categorystatus
     * @return type                   
     */            
	public function setCategorystatus($categorystatus){
		$this->categorystatus = (int) $categorystatus;
	}
    /**
     * Get categorystatus
     *
     * @return int
     */          
	public function getCategorystatus(){
		return $this->categorystatus;
	}
}

?>