<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

interface CategoryInterface{

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);

    /**
     * Get id
     *
     * @return int
     */          
   public function getId();

    /**
     * Set idparent
     *
     * @param int $idparent
     * @return type                   
     */            
   public function setIdparent($idparent);

    /**
     * Get idparent
     *
     * @return int
     */          
   public function getIdparent();

    /**
     * Set name
     *
     * @param varchar $name
     * @return type                   
     */            
   public function setName($name);

    /**
     * Get name
     *
     * @return varchar
     */          
   public function getName();

    /**
     * Set description
     *
     * @param text $description
     * @return type                   
     */            
   public function setDescription($description);

    /**
     * Get description
     *
     * @return text
     */          
   public function getDescription();

    /**
     * Set thumbimg
     *
     * @param varchar $thumbimg
     * @return type                   
     */            
   public function setThumbimg($thumbimg);

    /**
     * Get thumbimg
     *
     * @return varchar
     */          
   public function getThumbimg();

    /**
     * Set fullimg
     *
     * @param varchar $fullimg
     * @return type                   
     */            
   public function setFullimg($fullimg);

    /**
     * Get fullimg
     *
     * @return varchar
     */          
   public function getFullimg();

    /**
     * Set lastupdate
     *
     * @param int $lastupdate
     * @return type                   
     */            
   public function setLastupdate($lastupdate);

    /**
     * Get lastupdate
     *
     * @return int
     */          
   public function getLastupdate();

    /**
     * Set categoryorder
     *
     * @param int $categoryorder
     * @return type                   
     */            
   public function setCategoryorder($categoryorder);

    /**
     * Get categoryorder
     *
     * @return int
     */          
   public function getCategoryorder();

    /**
     * Set categorystatus
     *
     * @param int $categorystatus
     * @return type                   
     */            
   public function setCategorystatus($categorystatus);

    /**
     * Get categorystatus
     *
     * @return int
     */          
   public function getCategorystatus();

}

?>