<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Creditsperiods implements CreditsperiodsInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var varchar              
     */
      protected $name;  

    /**
     * @var int              
     */
      protected $fromdate;  

    /**
     * @var int              
     */
      protected $todate;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set name
     *
     * @param varchar $name
     * @return type                   
     */            
	public function setName($name){
		$this->name = (string) $name;
	}
    /**
     * Get name
     *
     * @return varchar
     */          
	public function getName(){
		return $this->name;
	}
    /**
     * Set fromdate
     *
     * @param int $fromdate
     * @return type                   
     */            
	public function setFromdate($fromdate){
		$this->fromdate = (int) $fromdate;
	}
    /**
     * Get fromdate
     *
     * @return int
     */          
	public function getFromdate(){
		return $this->fromdate;
	}
    /**
     * Set todate
     *
     * @param int $todate
     * @return type                   
     */            
	public function setTodate($todate){
		$this->todate = (int) $todate;
	}
    /**
     * Get todate
     *
     * @return int
     */          
	public function getTodate(){
		return $this->todate;
	}
}

?>