<?php

/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */

namespace Cscore\Model\Entity;

class Credits implements CreditsInterface {

    /**
     * @var int              
     */
    protected $id;

    /**
     * @var int              
     */
    protected $userid;

    /**
     * @var float              
     */
    protected $credit;

    /**
     * @var int              
     */
    protected $lastupdate;

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */
    public function setId($id) {
        $this->id = (int) $id;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set userid
     *
     * @param int $userid
     * @return type                   
     */
    public function setUserid($userid) {
        $this->userid = (int) $userid;
    }

    /**
     * Get userid
     *
     * @return int
     */
    public function getUserid() {
        return $this->userid;
    }

    /**
     * Set credit
     *
     * @param float $credit
     * @return type                   
     */
    public function setCredit($credit) {
        $this->credit = (float) $credit;
    }

    /**
     * Get credit
     *
     * @return float
     */
    public function getCredit() {
        return $this->credit;
    }

    /**
     * Set lastupdate
     *
     * @param int $lastupdate
     * @return type                   
     */
    public function setLastupdate($lastupdate) {
        $this->lastupdate = (int) $lastupdate;
    }

    /**
     * Get lastupdate
     *
     * @return int
     */
    public function getLastupdate() {
        return $this->lastupdate;
    }

}
