<?php

/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */

namespace Cscore\Model\Entity;

interface CreditshistoryInterface {

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */
    public function setId($id);

    /**
     * Get id
     *
     * @return int
     */
    public function getId();

    /**
     * Set idperiod
     *
     * @param int $idperiod
     * @return type                   
     */
    public function setIdperiod($idperiod);

    /**
     * Get idperiod
     *
     * @return int
     */
    public function getIdperiod();

    /**
     * Set idusername
     *
     * @param int $idusername
     * @return type                   
     */
    public function setIdusername($idusername);

    /**
     * Get idusername
     *
     * @return int
     */
    public function getIdusername();

    /**
     * Set credits
     *
     * @param float $credits
     * @return type                   
     */
    public function setCredits($credits);

    /**
     * Get credits
     *
     * @return float
     */
    public function getCredits();

    /**
     * Set payments
     *
     * @param int $payments
     * @return type                   
     */
    public function setPayments($payments);

    /**
     * Get payments
     *
     * @return int
     */
    public function getPayments();

    /**
     * 
     * @return int
     */
    public function getStatus();

    /**
     * 
     * @param int $status
     * @return \Cscore\Model\Entity\Creditshistory
     */
    public function setStatus($status);
}
