<?php

/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */

namespace Cscore\Model\Entity;

class Creditshistory implements CreditshistoryInterface {

    /**
     * @var int              
     */
    protected $id;

    /**
     * @var int              
     */
    protected $idperiod;

    /**
     * @var int              
     */
    protected $idusername;

    /**
     * @var float              
     */
    protected $credits;

    /**
     * @var int              
     */
    protected $payments;

    /**
     * @var int              
     */
    protected $status;

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */
    public function setId($id) {
        $this->id = (int) $id;
        return $this;
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Set idperiod
     *
     * @param int $idperiod
     * @return type                   
     */
    public function setIdperiod($idperiod) {
        $this->idperiod = (int) $idperiod;
        return $this;
    }

    /**
     * Get idperiod
     *
     * @return int
     */
    public function getIdperiod() {
        return $this->idperiod;
    }

    /**
     * Set idusername
     *
     * @param int $idusername
     * @return type                   
     */
    public function setIdusername($idusername) {
        $this->idusername = (int) $idusername;
        return $this;
    }

    /**
     * Get idusername
     *
     * @return int
     */
    public function getIdusername() {
        return $this->idusername;
    }

    /**
     * Set credits
     *
     * @param float $credits
     * @return type                   
     */
    public function setCredits($credits) {
        $this->credits = (float) $credits;
        return $this;
    }

    /**
     * Get credits
     *
     * @return float
     */
    public function getCredits() {
        return $this->credits;
    }

    /**
     * Set payments
     *
     * @param float $payments
     * @return type                   
     */
    public function setPayments($payments) {
        $this->payments = (float) $payments;
        return $this;
    }

    /**
     * Get payments
     *
     * @return float
     */
    public function getPayments() {
        return $this->payments;
    }

    /**
     * 
     * @return int
     */
    public function getStatus() {
        return $this->status;
    }

    /**
     * 
     * @param int $status
     * @return \Cscore\Model\Entity\Creditshistory
     */
    public function setStatus($status) {
        $this->status = $status;
        return $this;
    }

}
