<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

interface CreditsInterface{

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);

    /**
     * Get id
     *
     * @return int
     */          
   public function getId();

    /**
     * Set userid
     *
     * @param int $userid
     * @return type                   
     */            
   public function setUserid($userid);

    /**
     * Get userid
     *
     * @return int
     */          
   public function getUserid();

    /**
     * Set credit
     *
     * @param int $credit
     * @return type                   
     */            
   public function setCredit($credit);

    /**
     * Get credit
     *
     * @return int
     */          
   public function getCredit();

    /**
     * Set lastupdate
     *
     * @param int $lastupdate
     * @return type                   
     */            
   public function setLastupdate($lastupdate);

    /**
     * Get lastupdate
     *
     * @return int
     */          
   public function getLastupdate();

}

