<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

interface CreditsperiodsInterface{

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);

    /**
     * Get id
     *
     * @return int
     */          
   public function getId();

    /**
     * Set name
     *
     * @param varchar $name
     * @return type                   
     */            
   public function setName($name);

    /**
     * Get name
     *
     * @return varchar
     */          
   public function getName();

    /**
     * Set fromdate
     *
     * @param int $fromdate
     * @return type                   
     */            
   public function setFromdate($fromdate);

    /**
     * Get fromdate
     *
     * @return int
     */          
   public function getFromdate();

    /**
     * Set todate
     *
     * @param int $todate
     * @return type                   
     */            
   public function setTodate($todate);

    /**
     * Get todate
     *
     * @return int
     */          
   public function getTodate();

}

?>