<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Orderstatus implements OrderstatusInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var varchar              
     */
      protected $namestatus;  

    /**
     * @var text              
     */
      protected $description;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set namestatus
     *
     * @param varchar $namestatus
     * @return type                   
     */            
	public function setNamestatus($namestatus){
		$this->namestatus = (string) $namestatus;
	}
    /**
     * Get namestatus
     *
     * @return varchar
     */          
	public function getNamestatus(){
		return $this->namestatus;
	}
    /**
     * Set description
     *
     * @param text $description
     * @return type                   
     */            
	public function setDescription($description){
		$this->description = (string) $description;
	}
    /**
     * Get description
     *
     * @return text
     */          
	public function getDescription(){
		return $this->description;
	}
}

?>