<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

interface OrderhistoryInterface{

    /**
     * Set orderid
     *
     * @param int $orderid
     * @return type                   
     */            
   public function setOrderid($orderid);

    /**
     * Get orderid
     *
     * @return int
     */          
   public function getOrderid();

    /**
     * Set orderstatus
     *
     * @param int $orderstatus
     * @return type                   
     */            
   public function setOrderstatus($orderstatus);

    /**
     * Get orderstatus
     *
     * @return int
     */          
   public function getOrderstatus();

    /**
     * Set orderdate
     *
     * @param int $orderdate
     * @return type                   
     */            
   public function setOrderdate($orderdate);

    /**
     * Get orderdate
     *
     * @return int
     */          
   public function getOrderdate();

    /**
     * Set ip
     *
     * @param int $ip
     * @return type                   
     */            
   public function setIp($ip);

    /**
     * Get ip
     *
     * @return int
     */          
   public function getIp();

}

?>