<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Orderhistory implements OrderhistoryInterface{

    /**
     * @var int              
     */
      protected $orderid;  

    /**
     * @var int              
     */
      protected $orderstatus;  

    /**
     * @var int              
     */
      protected $orderdate;  

    /**
     * @var int              
     */
      protected $ip;  

    /**
     * Set orderid
     *
     * @param int $orderid
     * @return type                   
     */            
	public function setOrderid($orderid){
		$this->orderid = (int) $orderid;
	}
    /**
     * Get orderid
     *
     * @return int
     */          
	public function getOrderid(){
		return $this->orderid;
	}
    /**
     * Set orderstatus
     *
     * @param int $orderstatus
     * @return type                   
     */            
	public function setOrderstatus($orderstatus){
		$this->orderstatus = (int) $orderstatus;
	}
    /**
     * Get orderstatus
     *
     * @return int
     */          
	public function getOrderstatus(){
		return $this->orderstatus;
	}
    /**
     * Set orderdate
     *
     * @param int $orderdate
     * @return type                   
     */            
	public function setOrderdate($orderdate){
		$this->orderdate = (int) $orderdate;
	}
    /**
     * Get orderdate
     *
     * @return int
     */          
	public function getOrderdate(){
		return $this->orderdate;
	}
    /**
     * Set ip
     *
     * @param int $ip
     * @return type                   
     */            
	public function setIp($ip){
		$this->ip = (int) $ip;
	}
    /**
     * Get ip
     *
     * @return int
     */          
	public function getIp(){
		return $this->ip;
	}
}

?>