<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Orderitem implements OrderitemInterface{

    /**
     * @var int              
     */
      protected $orderid;  

    /**
     * @var int              
     */
      protected $productid;  

    /**
     * @var int              
     */
      protected $quantity;  

    /**
     * @var float              
     */
      protected $price;  

    /**
     * @var float              
     */
      protected $fees;  

    /**
     * @var float              
     */
      protected $linetotal;  

    /**
     * Set orderid
     *
     * @param int $orderid
     * @return type                   
     */            
	public function setOrderid($orderid){
		$this->orderid = (int) $orderid;
	}
    /**
     * Get orderid
     *
     * @return int
     */          
	public function getOrderid(){
		return $this->orderid;
	}
    /**
     * Set productid
     *
     * @param int $productid
     * @return type                   
     */            
	public function setProductid($productid){
		$this->productid = (int) $productid;
	}
    /**
     * Get productid
     *
     * @return int
     */          
	public function getProductid(){
		return $this->productid;
	}
    /**
     * Set quantity
     *
     * @param int $quantity
     * @return type                   
     */            
	public function setQuantity($quantity){
		$this->quantity = (int) $quantity;
	}
    /**
     * Get quantity
     *
     * @return int
     */          
	public function getQuantity(){
		return $this->quantity;
	}
    /**
     * Set price
     *
     * @param float $price
     * @return type                   
     */            
	public function setPrice($price){
		$this->price = (float) $price;
	}
    /**
     * Get price
     *
     * @return float
     */          
	public function getPrice(){
		return $this->price;
	}
    /**
     * Set fees
     *
     * @param float $fees
     * @return type                   
     */            
	public function setFees($fees){
		$this->fees = (float) $fees;
	}
    /**
     * Get fees
     *
     * @return float
     */          
	public function getFees(){
		return $this->fees;
	}
    /**
     * Set linetotal
     *
     * @param float $linetotal
     * @return type                   
     */            
	public function setLinetotal($linetotal){
		$this->linetotal = (float) $linetotal;
	}
    /**
     * Get linetotal
     *
     * @return float
     */          
	public function getLinetotal(){
		return $this->linetotal;
	}
}

?>