<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Paymentmethod implements PaymentmethodInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var varchar              
     */
      protected $name;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set name
     *
     * @param varchar $name
     * @return type                   
     */            
	public function setName($name){
		$this->name = (string) $name;
	}
    /**
     * Get name
     *
     * @return varchar
     */          
	public function getName(){
		return $this->name;
	}
}

?>