<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Payment implements PaymentInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var int              
     */
      protected $methodid;  

    /**
     * @var int              
     */
      protected $orderid;  

    /**
     * @var int              
     */
      protected $userid;  

    /**
     * @var float              
     */
      protected $total;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set methodid
     *
     * @param int $methodid
     * @return type                   
     */            
	public function setMethodid($methodid){
		$this->methodid = (int) $methodid;
	}
    /**
     * Get methodid
     *
     * @return int
     */          
	public function getMethodid(){
		return $this->methodid;
	}
    /**
     * Set orderid
     *
     * @param int $orderid
     * @return type                   
     */            
	public function setOrderid($orderid){
		$this->orderid = (int) $orderid;
	}
    /**
     * Get orderid
     *
     * @return int
     */          
	public function getOrderid(){
		return $this->orderid;
	}
    /**
     * Set userid
     *
     * @param int $userid
     * @return type                   
     */            
	public function setUserid($userid){
		$this->userid = (int) $userid;
	}
    /**
     * Get userid
     *
     * @return int
     */          
	public function getUserid(){
		return $this->userid;
	}
    /**
     * Set total
     *
     * @param float $total
     * @return type                   
     */            
	public function setTotal($total){
		$this->total = (float) $total;
	}
    /**
     * Get total
     *
     * @return float
     */          
	public function getTotal(){
		return $this->total;
	}
}

?>