<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

interface PaymentmethodInterface{

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);

    /**
     * Get id
     *
     * @return int
     */          
   public function getId();

    /**
     * Set name
     *
     * @param varchar $name
     * @return type                   
     */            
   public function setName($name);

    /**
     * Get name
     *
     * @return varchar
     */          
   public function getName();

}

?>