<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

interface PaymentInterface{

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);

    /**
     * Get id
     *
     * @return int
     */          
   public function getId();

    /**
     * Set methodid
     *
     * @param int $methodid
     * @return type                   
     */            
   public function setMethodid($methodid);

    /**
     * Get methodid
     *
     * @return int
     */          
   public function getMethodid();

    /**
     * Set orderid
     *
     * @param int $orderid
     * @return type                   
     */            
   public function setOrderid($orderid);

    /**
     * Get orderid
     *
     * @return int
     */          
   public function getOrderid();

    /**
     * Set userid
     *
     * @param int $userid
     * @return type                   
     */            
   public function setUserid($userid);

    /**
     * Get userid
     *
     * @return int
     */          
   public function getUserid();

    /**
     * Set total
     *
     * @param float $total
     * @return type                   
     */            
   public function setTotal($total);

    /**
     * Get total
     *
     * @return float
     */          
   public function getTotal();

}

?>