<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Productprice implements ProductpriceInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var int              
     */
      protected $productid;  

    /**
     * @var float              
     */
      protected $price;  

    /**
     * @var varchar              
     */
      protected $currency;  

    /**
     * @var int              
     */
      protected $lastupdate;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set productid
     *
     * @param int $productid
     * @return type                   
     */            
	public function setProductid($productid){
		$this->productid = (int) $productid;
	}
    /**
     * Get productid
     *
     * @return int
     */          
	public function getProductid(){
		return $this->productid;
	}
    /**
     * Set price
     *
     * @param float $price
     * @return type                   
     */            
	public function setPrice($price){
		$this->price = (float) $price;
	}
    /**
     * Get price
     *
     * @return float
     */          
	public function getPrice(){
		return $this->price;
	}
    /**
     * Set currency
     *
     * @param varchar $currency
     * @return type                   
     */            
	public function setCurrency($currency){
		$this->currency = (string) $currency;
	}
    /**
     * Get currency
     *
     * @return varchar
     */          
	public function getCurrency(){
		return $this->currency;
	}
    /**
     * Set lastupdate
     *
     * @param int $lastupdate
     * @return type                   
     */            
	public function setLastupdate($lastupdate){
		$this->lastupdate = (int) $lastupdate;
	}
    /**
     * Get lastupdate
     *
     * @return int
     */          
	public function getLastupdate(){
		return $this->lastupdate;
	}
}

?>