<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Productcategory implements ProductcategoryInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var int              
     */
      protected $productid;  

    /**
     * @var int              
     */
      protected $categoryid;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set productid
     *
     * @param int $productid
     * @return type                   
     */            
	public function setProductid($productid){
		$this->productid = (int) $productid;
	}
    /**
     * Get productid
     *
     * @return int
     */          
	public function getProductid(){
		return $this->productid;
	}
    /**
     * Set categoryid
     *
     * @param float $categoryid
     * @return type                   
     */            
	public function setCategoryid($categoryid){
		$this->categoryid = (int) $categoryid;
	}
    /**
     * Get price
     *
     * @return float
     */          
	public function getCategoryid(){
		return $this->categoryid;
	}
 
}

?>