<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

interface ProductcategoryInterface{

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);

    /**
     * Get id
     *
     * @return int
     */          
   public function getId();

    /**
     * Set productid
     *
     * @param int $productid
     * @return type                   
     */            
   public function setProductid($productid);

    /**
     * Get productid
     *
     * @return int
     */          
   public function getProductid();

    /**
     * Set categoryid
     *
     * @param int $categoryid
     * @return type                   
     */            
   public function setCategoryid($categoryid);

    /**
     * Get categoryid
     *
     * @return int
     */          
   public function getCategoryid();



}

?>