<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

class Product implements ProductInterface{

    /**
     * @var int              
     */
      protected $id;  

    /**
     * @var varchar              
     */
      protected $sku;  

    /**
     * @var varchar              
     */
      protected $othersku;  

    /**
     * @var text              
     */
      protected $description;  

    /**
     * @var varchar              
     */
      protected $thumbimage;  

    /**
     * @var varchar              
     */
      protected $fullimage;  

    /**
     * @var int              
     */
      protected $lastupdate;  

    /**
     * @var tinyint              
     */
      protected $productstatus;  

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
	public function setId($id){
		$this->id = (int) $id;
	}
    /**
     * Get id
     *
     * @return int
     */          
	public function getId(){
		return $this->id;
	}
    /**
     * Set sku
     *
     * @param varchar $sku
     * @return type                   
     */            
	public function setSku($sku){
		$this->sku = (string) $sku;
	}
    /**
     * Get sku
     *
     * @return varchar
     */          
	public function getSku(){
		return $this->sku;
	}
    /**
     * Set othersku
     *
     * @param varchar $othersku
     * @return type                   
     */            
	public function setOthersku($othersku){
		$this->othersku = (string) $othersku;
	}
    /**
     * Get othersku
     *
     * @return varchar
     */          
	public function getOthersku(){
		return $this->othersku;
	}
    /**
     * Set description
     *
     * @param text $description
     * @return type                   
     */            
	public function setDescription($description){
		$this->description = (string) $description;
	}
    /**
     * Get description
     *
     * @return text
     */          
	public function getDescription(){
		return $this->description;
	}
    /**
     * Set thumbimage
     *
     * @param varchar $thumbimage
     * @return type                   
     */            
	public function setThumbimage($thumbimage){
		$this->thumbimage = (string) $thumbimage;
	}
    /**
     * Get thumbimage
     *
     * @return varchar
     */          
	public function getThumbimage(){
		return $this->thumbimage;
	}
    /**
     * Set fullimage
     *
     * @param varchar $fullimage
     * @return type                   
     */            
	public function setFullimage($fullimage){
		$this->fullimage = (string) $fullimage;
	}
    /**
     * Get fullimage
     *
     * @return varchar
     */          
	public function getFullimage(){
		return $this->fullimage;
	}
    /**
     * Set lastupdate
     *
     * @param int $lastupdate
     * @return type                   
     */            
	public function setLastupdate($lastupdate){
		$this->lastupdate = (int) $lastupdate;
	}
    /**
     * Get lastupdate
     *
     * @return int
     */          
	public function getLastupdate(){
		return $this->lastupdate;
	}
    /**
     * Set productstatus
     *
     * @param tinyint $productstatus
     * @return type                   
     */            
	public function setProductstatus($productstatus){
		$this->productstatus = (int) $productstatus;
	}
    /**
     * Get productstatus
     *
     * @return tinyint
     */          
	public function getProductstatus(){
		return $this->productstatus;
	}
}

?>