<?php
/**
 * Configuration file generated by ApiTool
 *
 * @see https://github.com/CookieShop/apitools.git
 */


namespace Cscore\Model\Entity;

interface ProductInterface{

    /**
     * Set id
     *
     * @param int $id
     * @return type                   
     */            
   public function setId($id);

    /**
     * Get id
     *
     * @return int
     */          
   public function getId();

    /**
     * Set sku
     *
     * @param varchar $sku
     * @return type                   
     */            
   public function setSku($sku);

    /**
     * Get sku
     *
     * @return varchar
     */          
   public function getSku();

    /**
     * Set othersku
     *
     * @param varchar $othersku
     * @return type                   
     */            
   public function setOthersku($othersku);

    /**
     * Get othersku
     *
     * @return varchar
     */          
   public function getOthersku();

    /**
     * Set description
     *
     * @param text $description
     * @return type                   
     */            
   public function setDescription($description);

    /**
     * Get description
     *
     * @return text
     */          
   public function getDescription();

    /**
     * Set thumbimage
     *
     * @param varchar $thumbimage
     * @return type                   
     */            
   public function setThumbimage($thumbimage);

    /**
     * Get thumbimage
     *
     * @return varchar
     */          
   public function getThumbimage();

    /**
     * Set fullimage
     *
     * @param varchar $fullimage
     * @return type                   
     */            
   public function setFullimage($fullimage);

    /**
     * Get fullimage
     *
     * @return varchar
     */          
   public function getFullimage();

    /**
     * Set lastupdate
     *
     * @param int $lastupdate
     * @return type                   
     */            
   public function setLastupdate($lastupdate);

    /**
     * Get lastupdate
     *
     * @return int
     */          
   public function getLastupdate();

    /**
     * Set productstatus
     *
     * @param tinyint $productstatus
     * @return type                   
     */            
   public function setProductstatus($productstatus);

    /**
     * Get productstatus
     *
     * @return tinyint
     */          
   public function getProductstatus();

}

?>