<?php
	$title = 'Login';
	$this->headTitle($title);
	
	$form->setAttribute('action', $this->url('auth', array('action' => 'login')));
	$form->setAttribute('class', 'form-horizontal');
	
	$form->prepare();

	echo $this->form()->openTag($form);
?>
	<div class="logo"></div>
<?php
	echo $this->formRow($form->get('username'));
	echo $this->formRow($form->get('password'));
	echo $this->formSubmit($form->get('submit'));
?>
	<div class="error-message">
<?php
	if(isset($messages)){
		switch ($errorcode) {
			case -1:
				echo '<p class="text-danger">Este usuario no existe en el sistema.</p>';
				break;
				
			case -3:
				echo '<p class="text-warning">La contraseña es inválida.</p>';
				break;
			
			default:
				
				break;
		}
	}
?>
	</div>
	<p class="forgotten-link">	
		<a href="<?= $this->url('user', array('action'=>'forgotten-password')); ?>">¿Olvidó su contraseña?</a>
	</p>
<?php
	echo $this->form()->closeTag();