<div class="content">
	<a class="regresar" href="#">Regresar</a>
	<h1>Estado de cuenta</h1>
	
	<?php if($this->zfcUserIdentity()->getGid() == 3): ?>
	<a class="managerlink" href="<?php echo $this->basePath('registro') ?>">Alta de vendedor</a>
	<a class="managerlink" href="<?php echo $this->url('zfcuser/perfil') ?>">Ver datos de perfil</a>
	<?php endif ?>
	<a class="managerlink" href="<?php echo $this->basePath('historial') ?>">Historial de canje</a>
	<?php

	foreach ($cuotas as $key => $value):

	?>

	<div class="table_tl" >
		<table >
			<tr>
				<td><?php echo $meses_text[$key] ?></td>
			</tr>
		</table>
		<table >
			<tr>
				<td width="25%">Concepto</td>
				<td width="25%"> Cuota Mensual</td>
				<td width="25%"> Venta Lograda</td>
				<td width="25%"> Puntos Generados</td>
			</tr>
			<?php foreach($value["data"] as $cuota): 

			?>
			<tr>
				<td><?php echo $cuota["familia_text"] ?></td>
				<td><?php echo $cuota["cuota"] ?></td>
				<td><?php echo $cuota["venta"] ?></td>
				<td><?php echo $cuota["puntos"] ?></td>
			</tr>
			<?php endforeach ?>
			
		</table>	
	</div>	

	<?php endforeach ?>
	

	<div class="databox" align="center">
		Puntos ganados: <span class="puntos"><?php echo number_format($creditos["ganados"]) ?></span> 
	</div>
	<div class="clear"></div>
	<div class="databox" align="center">
		Puntos canjeados: <span class="puntos"><?php echo number_format($creditos["canjeados"]) ?></span> 
	</div>
	<div class="clear"></div>
	<div class="databox" align="center">
		Puntos disponibles: <span class="puntos"><?php echo number_format($creditos["actuales"]) ?></span>
	</div>
	<div class="clear"></div>
</div>