<center>
	<h1 style="font:bold 150px Arial, Helvetica, sans-serif; display:block; letter-spacing:-10px;color:#666; margin:0px; padding:0px; padding-top:40px;line-height:100px;">404</h1>

    <h4 style="font:normal 20px Arial, Helvetica, sans-serif; color:#999; margin-bottom:30px;">
    	&iexcl;Ha ocurrido un error!
    	<?php
		$reasonMessage= '';
		switch ($this->reason) {
		    case 'error-controller-cannot-dispatch':
		        $reasonMessage = $this->translate('The requested controller was unable to dispatch the request.');
		        break;
		    case 'error-controller-not-found':
		        $reasonMessage = $this->translate('The requested controller could not be mapped to an existing controller class.');
		        break;
		    case 'error-controller-invalid':
		        $reasonMessage = $this->translate('The requested controller was not dispatchable.');
		        break;
		    case 'error-router-no-match':
		    	$reasonMessage = "La URL solicitada no ha sido encontrada.";
		        break;
		    default:
		        $reasonMessage = $this->translate('We cannot determine at this time why a 404 was generated.');
		        break;
		}
		?>

		<p><?php echo $reasonMessage ?></p>
    </h4>

    
    <a href="#" onclick="window.history.go(-1)" style="font: bold 20px Arial,Helvetica, sans-serif;background: #E09101;padding: 10px;color: #FFF;text-decoration: NONE;">Regresar</a>
</center>