<?php
	$action 	= $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()->getParam('action', 'index');
	$controller = $this->getHelperPluginManager()->getServiceLocator()->get('application')->getMvcEvent()->getRouteMatch()->getParam('controller', 'index');
	$login_class = ($controller == "Application\Controller\Auth") ? "login-action" : "";

	switch ($controller) {
		case 'Application\Controller\Index':
			$view_class = "index";
		break;
		
		case 'Application\Controller\Product':
			$view_class = "product";
		break;
		
		case 'Application\Controller\Album':
			$view_class = "album";
		break;

		case 'Application\Controller\User':
			$view_class = "user";
		break;

		case 'Application\Controller\Categories':
			$view_class = "categories";
		break;

		case 'Application\Controller\Collections':
			$view_class = "collections";
		break;
		
		default:
		
		break;
	}

	if($view_class == 'user' && $action == 'forgotten-password'){
		$login_class = 'login-action';
	}

?>
<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('APP URREA')->setSeparator(' | ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        				->prependStylesheet($this->basePath() . '/css/style.css')
		                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
		?>
		<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
		
        <!-- Scripts -->
        <?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/script.js')
			->prependFile($this->basePath() . '/js/jquery.easypiechart.js')
			->prependFile($this->basePath() . '/js/additional-methods.js')
			->prependFile($this->basePath() . '/js/jquery.validate.js')
			->prependFile($this->basePath() . '/js/jquery.form.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="<?php echo $login_class; ?> ">
    	<?php if($login_class != "login-action"){ ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/urrea_logo.png') ?>" alt="URREA Catálogo"/></a>
                </div>
                <ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<span class="glyphicon glyphicon-user"></span> 
							<?= $this->identity()->username; ?> <span class="caret"></span>
						</a>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="<?php echo $this->url('user') ?>"><i class="fa fa-user"></i> Información de usuario</a>
							</li>
							<li>
								<a href="<?php echo $this->url('user', array('controller' => 'user', 'action' => 'restore-password'));?>">
									<i class="fa fa-lock"></i> Cambiar contraseña
								</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="#" onclick='return false' data-toggle="modal" data-target="#acerca">
									<i class="fa fa-info-circle"></i> Acerca de
								</a>
								
							</li>
							<li>
								<a href="#" onclick='return false' data-toggle="modal" data-target="#soporte">
									<i class="fa fa-life-ring"></i> Ayuda y soporte técnico
								</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="<?php echo $this->url('auth', array('controller' => 'auth', 'action' => 'logout'));?>">
									<i class="fa fa-power-off"></i> Logout
								</a>
							</li>
						</ul>
					</li>
				</ul>
            </div>
        </nav>
        <div class="clearfix"></div>
        <div id="content" class="container">
        	<!-- container -->
			<div class="sidebar">
				<ul class="nav nav-pills nav-stacked">
					<li>
						<a href="<?= $this->url('home', array('controller' => 'index', 'action' => 'index'));?>" title="Dashboard" class="dashboard link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-tasks fa-lg"></i>
						</a>
						<a href="<?= $this->url('products', array('controller' => 'product', 'action' => 'index'));?>" title="Productos" class="products link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-tint fa-lg"></i>
						</a>
						<a href="<?= $this->url('categories', array('controller' => 'categories', 'action' => 'index'));?>" title="Categorías" class="categories link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-tags fa-lg"></i>
						</a>
						<a href="<?= $this->url('collections', array('controller' => 'categories', 'action' => 'index'));?>" title="Colecciones" class="collections link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-book fa-lg"></i>
						</a>
						<a href="<?= $this->url('stages', array('controller' => 'stages', 'action' => 'index'));?>" title="Escenarios" title="Escenarios" class="stages link_tooltip" data-toggle="tooltip" data-placement="right" >
							<i class="fa fa-image fa-lg"></i>
						</a>
					</li>
				</ul>
			</div>
			<div class="right_panel"><?php echo $this->content; ?></div>
			<!-- /container -->
			
	        <!-- Modal Acerca de -->
			<div class="modal fade" id="acerca" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-body">
							<div class="hoppercat_logo"></div>
							<p class="body_text">
								Versión 1.0.0 (1.0.0)<br />
								Desarrollado por <a href="http://hoppercat.com">Hoppercat</a> para Urrea<br />
								Copyright &copy; 2014
							</p>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
						</div>
					</div>
				</div>
			</div>
			<!-- Modal Reportar un problema -->
			<div class="modal fade" id="soporte" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<form class="form-horizontal" id="support-form" role="form" action="<?= $this->basePath(); ?>/soporte.php" method="post">
							<div class="modal-header">
								<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
								<h4 class="modal-title" id="myModalLabel">Solicitar ayuda técnica</h4>
							</div>
							<div class="modal-body">
								<p class="lead">Enviar un mensaje a Hoppercat para notificar de un problema con el sistema.</p>
								<div class="fields">
										<input type="text" class="form-control" name="name" required="required" placeholder="Nombre completo"/>
										<input type="email" class="form-control" name="email" required="required" placeholder="Correo electrónico"/>
										<input type="text" class="form-control" name="phone" placeholder="Teléfono"/>
										<textarea rows="4" cols="50" class="form-control" name="details" placeholder="Detalles del problema"></textarea>
									
								</div>
								<div class="clearfix"></div>
								<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
								<button type="submit" class="btn btn-primary">Enviar</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
        <footer>
            <p class="container">&copy; <?php echo date('Y') ?> <a href="http://hoppercat.com">HopperCat</a>. <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
        <?php }else{ ?>
        <div class="container">
        	<?php echo $this->content; ?>
        </div>
        <?php } ?>
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript" src="<?= $this->basePath();?>/js/bootstrap.min.js"></script>
    </body>
</html>
