<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php date_default_timezone_set('America/Mexico_City') ?>
        <?php echo $this->headTitle($this->translate('Brilla con Tecnolite'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/sitio.css')
        ?>
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css" />
		<!-- <script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function() {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-54587227-1', 'auto');
            ga('send', 'pageview');
        </script>-->
    </head>
    <body>
        <header class="header">
			<div align="center">
				<a href="<?php echo $this->basePath(); ?>">
					<img src="<?php echo $this->basePath(); ?>/images/site_logo.jpg" width="404" height="210" alt="logo">
				</a>
			</div>
		</header>
        <section>
            <?php echo $this->content; ?>
        </section>  
        <div class="clear">
		   	<p>&nbsp;</p>
		   	<p>&nbsp;</p>
	 	</div>
	 	<div class="footer" align="center">
	 		<div class="ft_legal"><a href="#" class="ft">Aviso de privacidad</a> <a href="#" class="ft">Terminos y condiciones del programa</a></strong><br>
			    D.R. © Copyright 2013.  Derechos Reservados.  Adventa y Adbox son marcas registradas de Publigraphics S.A. de C.V.<br>
			  Quedan reservados todos los derechos de edición, copia o reproducción parcial o total.
	  		</div>
	  	</div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
        <script type="text/javascript">
            $(function(){
                $( "#birthdate" ).datepicker({
                    dateFormat: 'dd/mm/yy',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-100:+0"
                });
            });
        </script>
    </body>
</html>
