<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php date_default_timezone_set('America/Mexico_City') ?>
        <?php echo $this->headTitle($this->translate('Brilla con Tecnolite'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bjqs.css')
                ->prependStylesheet($this->basePath() . '/css/branimate.css')
                ->prependStylesheet($this->basePath() . '/css/tables.css')
                ->prependStylesheet($this->basePath() . '/css/sitio.css')
                ->prependStylesheet('https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css')
        ?>
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        		->prependFile($this->basePath() . '/js/functions.js')
                ->prependFile($this->basePath() . '/js/bjqs-1.3.min.js')
                ->prependFile($this->basePath() . '/js/facturacion.js')
                ->prependFile($this->basePath() . '/js/validator.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/jqueryValidator/localization/methods_es_CL.js')
                ->prependFile($this->basePath() . '/js/jqueryValidator/localization/messages_es.js')
                ->prependFile($this->basePath() . '/js/jqueryValidator/additional-methods.js')
                ->prependFile($this->basePath() . '/js/jqueryValidator/jquery.validate.js')
                ->prependFile('https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js')
                ->prependFile($this->basePath() . '/js/jquery-1.7.1.min.js')
        ?>

        <!-- <script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function() {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-54587227-1', 'auto');
            ga('send', 'pageview');
        </script>-->
    </head>
    <body>
        <header class="header">
        <div id="base_url" data-href="<?php echo $this->url('home') ?>"></div>
        <?php if (!empty($this->barUser['displayName'])): ?>
			<a href="<?php echo $this->url('home') ?>" class="logo"></a>
			<div class="userdata">
				<a class="genbtn" href="<?php echo $this->url('zfcuser/logout') ?>">Salir</a>
			  	<div class="user" align="center">Usuario: <span class="username"><?php echo $this->barUser['displayName']; ?></span></div>
			  	<div class="databox" align="center">Puntos Disponibles: <span class="puntos"><?php echo number_format(floor($this->barCredit['credit'])); ?></span></div>
			  	<a class="cartbtn" href="<?php echo $this->basePath('carrito') ?>">Carrito de canje</a>
			</div>
		<?php else: ?>
			<div style="text-align: center">
				<a href="<?php echo $this->basePath(); ?>">
					<img src="<?php echo $this->basePath(); ?>/images/site_logo.jpg" width="404" height="210" alt="logo">
				</a>
			</div>
		<?php endif ?>
		</header>
		<?php if (!empty($this->barUser['displayName'])): ?>
		<?php $partial = array('layout/topnav.phtml', 'default') ?>
		<?php $this->navigation('navigation')->menu()->setPartial($partial) ?>
		<?php echo $this->navigation('navigation')->menu()->render() ?>
  		<?php endif ?>
        <section>
            <?php echo $this->content; ?>
        </section>  
        <div class="clear">
		   	<p>&nbsp;</p>
		   	<p>&nbsp;</p>
	 	</div>
	 	<div class="footer" align="center">
	 		<div class="ft_legal"><a href="#" class="ft">Aviso de privacidad</a> <a href="#" class="ft">Terminos y condiciones del programa</a></strong><br>
			    D.R. © Copyright 2013.  Derechos Reservados.  Adventa y Adbox son marcas registradas de Publigraphics S.A. de C.V.<br>
			  Quedan reservados todos los derechos de edición, copia o reproducción parcial o total.
	  		</div>
	  	</div>
    </body>
</html>
