 <div class="menu_base">
  	<div class="menu_container" align="center">
    	<?php $count = 0 ?>
    	<?php $gid = $this->zfcUserIdentity()->getGid() ?>
	    <?php foreach ($this->container as $page): ?>
	        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
	        <?php // when using partials we need to manually check for ACL conditions ?>
	        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
	        <?php $hasChildren = $page->hasPages() ?>
	        
        	<?php if($page->getId() == 6){ ?>

        		<?php if($gid == 2){ ?>
        				<a class="menu_item unav_<?php echo $page->getId()?>_<?php echo $gid ?>  
        					<?php if($page->isActive()) echo "menu_activo"?>" href="<?php echo $page->getHref() ?>">
			    	    	<?php echo $this->translate($page->getLabel()) ?>
				        </a>
        		<?php } ?>

        	<?php }elseif($page->getId() == 4){ ?>

        		<?php if($gid != 2){ ?>
        				<a class="menu_item  unav_<?php echo $page->getId()?>_<?php echo $gid ?>
        					<?php if($page->isActive()) echo "menu_activo"?>" href="<?php echo $page->getHref() ?>">
			    	    	<?php echo $this->translate($page->getLabel()) ?>
				        </a>
        		<?php } ?>

        	<?php }else{ ?>
		        <a class="menu_item unav_<?php echo $page->getId()?>_<?php echo $gid ?> <?php if($page->isActive()) echo "menu_activo"?>" href="<?php echo $page->getHref() ?>">
	    	    	<?php echo $this->translate($page->getLabel()) ?>
		        </a>
        	<?php } ?>

	        
	        <?php $count++ ?>
	    <?php endforeach ?>
	</div>
</div>