 <div class="menu_base">
  	<div class="menu_container" align="center">
    	<?php $count = 0 ?>
	    <?php foreach ($this->container as $page): ?>
	        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
	        <?php // when using partials we need to manually check for ACL conditions ?>
	        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
	        <?php $hasChildren = $page->hasPages() ?>
	        
	        <a class="menu_item <?php if($page->isActive()) echo "menu_activo"?>" href="<?php echo $page->getHref() ?>">
	        	<?php echo $this->translate($page->getLabel()) ?>
	        </a>
	        
	        <?php $count++ ?>
	    <?php endforeach ?>
	</div>
</div>