<div class="content">
	<div id="wrapper">
		<h1 align="center">
			<img src="<?php echo $this->basePath('images/mecanica/Mecanica_title.jpg') ?>" width="404" height="62" alt="titulo">
		</h1>
		<p class="desc">&nbsp;</p>
		<div class="animateblock centerleft">
			<img src="<?php echo $this->basePath('images/mecanica/como-participas.jpg') ?>" alt="macbook icon">
		</div>
		<div class="animateblock centerleft">
	    	<img src="<?php echo $this->basePath('images/mecanica/mecanica.jpg') ?>" alt="macbook icon">
	    </div>
	    <div class="animateblock centerleft">
	      	<img src="<?php echo $this->basePath('images/mecanica/mecanica-2.jpg') ?>">
	    </div>
	    <br><br>
	    <div class="animateblock size">
	      	<img src="<?php echo $this->basePath('images/mecanica/mecanica-3.jpg') ?>" alt="colorful balloons">
	      	<!-- https://www.iconfinder.com/icons/82288/baloon_travel_icon -->
	    </div>
	    <div class="animateblock left">
	    	<img src="<?php echo $this->basePath('images/mecanica/mecanica-4.jpg') ?>" alt="white ipod dock">
	    	<!-- https://www.iconfinder.com/icons/34331/apple_dock_ipod_icon -->
	    </div>
	    <br><br>
	    <div class="animateblock size">
	    	<img src="<?php echo $this->basePath('images/mecanica/mecanica-5.jpg') ?>" alt="colorful balloons">
	    	<!-- https://www.iconfinder.com/icons/82288/baloon_travel_icon -->
	    </div>
	    <br><br>
	    <div class="animateblock centerleft">
	    	<img src="<?php echo $this->basePath('images/mecanica/mecanica-6.jpg') ?>" alt="macbook icon">
	    </div>
	    <div class="animateblock left">
	      	<img src="<?php echo $this->basePath('images/mecanica/mecanica-7.jpg') ?>" alt="white ipod dock">
	      	<!-- https://www.iconfinder.com/icons/34331/apple_dock_ipod_icon -->
	    </div>
    </div> 
</div> 