<div class="hero-unit">
	<p class="text-header">
    	<span class="titFel">M&oacute;dulo de reportes</span><br/> 
    		Aquí puede generar y descargar reportes de la plataforma.
    </p>

    <div class="content app_content" style="text-align: center;">
    	<div style="margin-top: 50px;"></div>
    	<a href="#" class="btn btn--tertiary btn-report btn-ventas">Master de ventas</a>
    	<a href="#" class="btn btn--tertiary btn-report btn-cuentas">Master de usuarios y edo de ctas</a>
    	<a href="#" class="btn btn--tertiary btn-report btn-users">Master de usuarios</a>
    	<a href="#" class="btn btn--tertiary btn-report btn-canjes">Master de canjes</a>
    </div>
</div>