<div class="content">
	<h1>Categorías</h1>
	<div class="categorias" align="center">
		<?php foreach ($categories as $category): ?>
		<div class="categoria" 
				style="background-image: url(<?php echo $this->basePath($category['thumb_img']) ?>);">
			<a href="<?php echo $this->basePath('productsc/' . $category['id']) ?>" class="cat_hover" >
				<?php echo $category['name'] ?>
			</a>
		</div>
		<?php endforeach ?>
	</div>
</div>