<!-- UX form -->
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('user', array('controller' => 'user', 'action' => 'forgotten-password')));
	$form->setAttribute('class', 'form-horizontal form-forgot-password max-340');
	$form->prepare();
	echo $this->form()->openTag($form);
?>
<div class="form-body">
	
    	<div class="logo"></div>
    <div class="capture">
    	<?php echo $this->formRow($form->get('usr_email')); ?>
        <!-- <input type="email" class="input-block-level" placeholder="Email"> -->
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <div class="separator">
            <span>Instrucciones</span>
        </div>
        <div class="instruct">
			Indique la dirección de correo electrónico del usuario administrador. Le enviaremos un mensaje con la nueva contraseña restablecida.
        </div>
    </div>
    <div class="text-confirm">
    	<?php
    		if(isset($message)){
				echo $message;
			}

    	?>
    </div>
</div>
<p class="forgotten-link">	
	<a href="<?= $this->url('auth', array('action'=>'login')); ?>"><i class="fa fa-chevron-left"></i> Regresar e iniciar sesión</a>
</p
<?php echo $this->form()->closeTag(); ?>