<?php
$title = 'Cambiar contraseña';
$this->headTitle($title);
echo "<br />";
?>
<div class="user-view view-container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<span class="glyphicon glyphicon-user"></span> <?= $title; ?>
		</div>
		<div class="panel-body">
			<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url('user', array('controller' => 'user', 'action' => 'restore-password')));
			$form->setAttribute('class', 'form-horizontal');
			$form->prepare();
			echo $this->form()->openTag($form);
			?>
			<div class="row">
				<div class="col-md-6">
					<?php 
						echo $this->formRow($form->get('password')); 
						echo $this->formRow($form->get('password_confirm'));
					?>
					<div class="text-confirm">
				    	<?php
				    		if(isset($message)){
								echo $message;
							}

				    	?>
				    </div>
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="button-set">
				<a href="<?= $this->url('user', array('action'=>'index')); ?>" class="btn btn-danger">
					<span class="glyphicon glyphicon-remove"></span> Cancelar
				</a>
				<button type="submit" id="btn-save" name="submit" class="btn btn-success">
					<span class="glyphicon glyphicon-floppy-disk"></span> Cambiar contraseña
				</button>
			</div>
			<?php echo $this->form()->closeTag(); ?>
			
		</div>
	</div>
</div>