<?php
$title = 'Mis &aacute;lbums';
$this->headTitle($title);
$url_order = 'ASC';  // the following lines
if ($order_by == 'title')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
elseif ($order_by == 'artist')
    $url_order = $order == 'ASC' ? 'DESC' : 'ASC';
?>
<div class="product-view view-container">
	<h1><?= $title; ?></h1>
	<p>
	    <a href="<?= $this->url('album', array('action'=>'add')); ?>">Nuevo &Aacute;lbum</a>
	</p>
	<table class="table">
	    <tr>
	        <th>
	            <a href="<?php echo $this->url('album', array('order_by' => 'title', 'order' => $url_order)); ?>">
	            	Title 
	            	<?php if ($order_by == 'title'): ?>
	            		<i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i>
	            	<?php endif; ?>
	            </a>
	        </th>
	        <th>
	            <a href="<?php echo $this->url('album', array('order_by' => 'artist', 'order' => $url_order)); ?>">Artist <?php if ($order_by == 'artist'): ?><i class="icon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
	        <th>&nbsp;</th>
	    </tr>
	    <?php foreach($paginator as $album){ ?>
	    <tr>
	        <td><?= $this->escapeHtml($album->title); ?></td>
	        <td><?= $this->escapeHtml($album->artist); ?></td>
	        <td>
	            <a href="<?php echo $this->url('album', array('action'=>'edit', 'id'=> $album->id)); ?>">Editar</a>
	            <a href="<?php echo $this->url('album', array('action'=>'delete', 'id'=> $album->id)); ?>">Eliminar</a>
	        </td>
	    </tr>
	    <?php } ?>
	</table>
	<?php
		echo $this->paginationControl(
	        $paginator, 'Sliding', 'paginator-slide', array('order_by' => $order_by, 'order' => $order)
	    );
	?>
</div>