<div class="content">
 <h1>Registrar Ventas</h1>
 <div align="center"><img src="<?php echo $this->basePath('images/registrar_ventas.jpg') ?>" width="849" height="144"></div>
 <div class="narrow">
 <div>
   <form name="form1" method="post" action="">
     <label>
       <div align="left"><span class="puntos"><span style="font-size:26px;">1 &nbsp;&nbsp;</span> Descarga</span> el formato de ventas 
         <a href="<?php echo $this->basePath('format/formato_resultados_mensuales.xls') ?>" id="button-download">Descargar</a>
       </div>
     </label>
   </form>
 </div>
 <div>
   <div align="left"><span class="puntos"><span style="font-size:26px;">2 &nbsp;&nbsp;</span> Llena</span> el formato de ventas </div>
 </div>
   	<?php
        // Init Form
        $form = $this->form;
        $form->setAttribute('class', 'form-inline');
        $form->setAttribute('id', 'formUploader');
        $form->setAttribute('action', $this->url('home') . 'registro-ventas/upload');
        $form->prepare();
        // Configure Errors Helper
        $errorsHelper = $this->plugin('formelementerrors');
        $errorsHelper
                ->setMessageOpenFormat('<div class="help-block">')
                ->setMessageSeparatorString('</div><div class="help-block">')
                ->setMessageCloseString('</div>');
    ?>
	<?php echo $this->form()->openTag($form); ?>
 <div>
   <div align="left">
   		<span class="puntos">
   			<span style="font-size:26px;">3 &nbsp;&nbsp;</span> Selecciona
   		</span> el mes de reporte de ventas 
   		<?php echo $this->formRow($form->get('month')) ?>
   </div>
 </div>
 <div>
   <div align="left"><span class="puntos"><span style="font-size:26px;">4 &nbsp;&nbsp;</span> Adjunta</span> el formato de ventas previamente llenado
   </div>
   <div style="margin: 10px auto;">
	    	<div class="form-group">
	            <?php
	            $elem = $form->get('archivo');
	            $errors = $elem->getMessages();
	            ?>
	        </div>
	        <div class="form-group">
	            <input type="hidden" name="user" value="<?php echo $user_id ?>" />
				<div class="fileUpload btn btn-primary">
				    <span>Seleccionar</span>
					<?php echo $this->formFile($elem); ?>
				</div>
	            <input id="uploadFile" placeholder="Escoge un archivo" disabled="disabled" />
	        	
	        	<button id="sendFile" class="save-btn">Guardar</button>

	        	<!-- <input type="submit" class="save-btn" value="Aceptar" /> -->
	        	<label id="nameError" class="error_label"></label>
	           
	        </div>
	        <!-- <button id="sendFactura" class="facturacion-btn">Aceptar</button> -->
	        <?php echo $this->form()->closeTag($form); ?>



			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById("uploadBtn").onchange = function () {
	    document.getElementById("uploadFile").value = this.value;
	};
</script>