<?php

$url = $this->basePath('historial');
//handle parameter get :)
$cat = $this->Categoryhelper();
?>
<?php if ($this->pageCount): ?>
<div class="pagination pagination-centered">
    <ul>
        <li<?php echo (isset($this->previous)) ? '' : " class='active'"; ?>>
            <a href="<?php echo $url.'/1'; ?>">Principio</a></li>
        <li<?php echo (isset($this->previous)) ? '' : " class='active'"; ?>>
            <a href="<?php echo $url.'/'.$this->previous; ?>">Anterior</a></li>
      <?php foreach ($this->pagesInRange as $page): ?>  
          <li<?php echo ($page != $this->current) ? '' : " class='active'"; ?>>
              <a href="<?php echo $url.'/'.$page; ?>"><?php echo $page; ?></a>
          </li>
      <?php endforeach; ?>
        <li<?php echo (isset($this->next)) ? '' : " class='active'"; ?>>
            <a href="<?php echo $url.'/'.$this->next; ?>" 
               title="Siguiente"> Siguiente</a></li>
      <li<?php echo (isset($this->next)) ? '' : " class='active'"; ?>>
          <a href="<?php echo $url.'/'.$this->pageCount; ?>"  
             title="Fin"> Ultimo</a></li>
    </ul>
</div>
<?php endif; ?>
