<?php
$url = $this->basePath('productsc');
//handle parameter get :)
$cat = $this->Categoryhelper();
?>
<?php if ($this->pageCount): ?>
    <br />
    <br />
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4 text-center subtitulo">
            <ul class="pagination">
        <!--        <li<?php echo (isset($this->previous)) ? '' : " class='active' style='display:none'"; ?>>
                    <a href="<?php echo $url . '/' . $cat . '/1'; ?>">Principio</a></li>-->
                <li <?php echo (isset($this->previous)) ? '' : " class='active' style='display:none'"; ?> >
                    <a href="<?php echo $url . '/' . $cat . '/' . $this->previous; ?>" class="anterior">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li<?php echo (isset($this->next)) ? '' : " class='active' style='display:none'"; ?>>
                    <a href="<?php echo $url . '/' . $cat . '/' . $this->next; ?>" title="Siguiente" class="siguiente">  
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
            <div style="margin-top:350px;"></div>
            <?php echo "<p>(" . $this->current . " / " . count($this->pagesInRange) . ")</p>"; ?>
        </div>
        <div class="col-md-4 subtitulo padPagina"></div>
    </div>
<?php endif; ?>