<?php $row = $this->producto; echo "<pre>";var_dump($row);die; ?>
<div class="content">
	<a class="regresar" href="#" onclick="window.history.go(-1); return false;">Regresar</a>
	<div class="product_desc_image">
		<img src="<?php echo $row['full_image'] ?>" width="430" height="455" alt="<?php echo $row['sku'] ?>">
	</div>
	<div class="product_desc">
		<div class="product_name_details"><?php echo $row['other_sku'] ?></div>
		<div class="product_text">Categoría: <span><?php echo $this->categoria ?></span></div>
		<div class="product_text">Descripción: </div>
		<div class="product_text"> <?php echo $row["description"] ?></div>
		<div class="product_name_details">Valor: <?php echo $row['price'] ?></div>
	</div>
	<p><a class="product_add_to_cart2" href="#">Agregar al carrito</a></p>
</div>



<br />
<br />
<section class="container">
    <div class="row">
        <div class="col-md-6 color-font-rosa producto-categoria">            
            <b>CATEGORÍA</b>
            <br /> 
            <span><?php echo $this->categoria ?></span>
        </div>        
        <div class="col-md-6 text-right">
            <a href="#" onclick="window.history.go(-1);
                    return false;" class="color-font">
                < Regresar
            </a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-6">        
            <div class="imgProducto">
                <a href="<?php echo $this->basePath('images/product/' . $row['full_image']); ?>" 
                   title="<?php echo $row['other_sku']; ?>" 
                   rel="lightbox[product504]">
                    <img src="<?php echo $this->basePath('images/product/' . $row['full_image']); ?>" 
                         data-src="holder.js/260x180"  
                         alt="<?php echo $row['other_sku']; ?>" 
                         class="img-responsive marCenter" />
                </a>
            </div>
        </div>
        <div class="col-md-6">     
            <div class="color-font-rosa detalle-titulo">
                <span>COD. <?php echo $row['sku']; ?></span><br />
                <span><?php echo $row['other_sku']; ?></span>
            </div>
            <!--<div class="precop text-right impact">-->
                <!--<b><?php // echo number_format($row['price']);      ?></b>-->
                <!--<img src="<?php // echo $this->basePath('images/lingote.png')      ?>" />-->
            <!--</div>-->
            <div><h4><?php echo $row['description']; ?></h4></div>
            <!--<div class="precop text-right"><strong><?php // echo $row['price'] . ' ' . $row['currency'];                     ?></strong></div>-->
            <br />
            <form action="<?php echo $this->basePath('carrito/2'); ?>" method="post"  class="addtocart_form" >
                <div class="row">
                    <div class="col-md-4">
                        <input type="number" name="quantity" min="0" max="50" value="1" class="form-control text-center">
                    </div>
                    <div class="col-md-8">
                        <input type="hidden" name="product_id" value="<?php echo $row['id']; ?>"/>
                        <input type="hidden" name="price" value="<?php echo $row['price']; ?>"/>
                        <input type="hidden" name="line_total" value="<?php echo $row['price']; ?>"/>
                        <div id="back" class="col-xs-4 col-md-4 text-center ">
                            <?php // if ($this->isCanjeOpen): ?>
                            <button id="addProduct" type="submit" class="btn btn-default producto-btn">
                                Agregar <span class="glyphicon glyphicon-shopping-cart"></span>
                            </button>    
                            <?php // endif ?>
                        </div>
                    </div>
                </div>

                <!--<label for="quantity504" class="quantity_box">Cantidad:&nbsp;</label>-->
                <!--<input type="hidden" class="inputboxquantity" size="4" id="quantity504" name="quantity" value="1" />-->
<!--                    <input type="hidden" class="quantity_box_button quantity_box_button_up" value="+" onclick="var qty_el = document.getElementById('quantity504');
                        var qty = qty_el.value;
                        if (!isNaN(qty))
                            qty_el.value++;
                        return false;" />-->
<!--                    <input type="hidden" class="quantity_box_button quantity_box_button_down"  value="-" onclick="var qty_el = document.getElementById('quantity504');
                        var qty = qty_el.value;
                        if (!isNaN(qty) && qty > 0)
                            qty_el.value--;
                        return false;" />-->

                <!--                        <div id="divAddCart" class="col-xs-4 col-md-4 text-center ">
                                            <a id="backButton" href="javascript:history.go(-1)">
                                                <img src="<?php // echo $this->basePath('images/anadir.png');   ?>" class="img-responsive marCenter"/>
                                            </a> 
                                        </div>
                                        <div id="divAddCart" class="col-xs-4 col-md-4 text-center ">
                                            <a id="backButton" href="javascript:history.go(-1)">
                                                <img src="<?php // echo $this->basePath('images/atras.png');   ?>" class="img-responsive marCenter"/>
                                            </a> 
                                        </div>-->
                <!--                    <div id="buttonsBar" class="row">
                                    </div>-->
            </form>
        </div>
    </div>
    <br />    
</section>
<script type="text/javascript">
    $(document).ready(function() {
        $("#addProduct").click(function() {
            $("#buttonsBar").css('display', 'none');
        });
        $("#backButton").click(function() {
            $("#buttonsBar").css('display', 'none');
        });
    });
</script>
