<div class="hero-unit">
	<p class="text-header">
    	<span class="titFel">ADMINISTRADOR DE DOCUMENTOS</span><br/> 
    		Aquí puedes administrar documentos, usuarios y reportes.
    </p>
    <a href="<?php echo $this->url('admin-aplicaciones') ?>" class="link_button">Cargar ventas de aplicaciones</a>
    <a href="#" class="link_button">Ver usuarios</a>
    <a href="#" class="link_button">Reportes</a>

</div>