<?php
$form->prepare();
$form->setAttribute('action', $this->url('complete'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'reg-form complete-form')
?>
<?php echo $this->form()->openTag($form) ?>
    <h1>Completar perfil</h1>

	<?php if(count($form->getMessages())): ?>
		<div class="alert-error">Ha ocurrido un error. Por favor verifique sus datos.</div>
	<?php endif ?>
    <div class="form-group">
        <?php echo $this->formRow($form->get('address')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('fullname')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('phone')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('cellphone')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('email')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('birthdate')) ?>
    </div>
    
    <div class="form-group" style="text-align: center;">
        <?php echo $this->formElement($form->get('btn_save')) ?>
    </div>
<?php echo $this->form()->closeTag() ?>