
<?php
$form->prepare();
$form->setAttribute('action', $this->url('registro'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'reg-form registration-form');
?>
<?php echo $this->form()->openTag($form) ?>
    <h1>Alta de vendedor</h1>
    <?php
     if(count($form->getMessages())): ?>
        <div class="alert-error">Ha ocurrido un error. Por favor verifique los datos.</div>
    <?php endif ?>
	<div class="form-group">
        <?php echo $this->formRow($form->get('fullname')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('phone')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('cellphone')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('email')) ?>
    </div>
	<div class="form-group">
        <?php echo $this->formRow($form->get('birthdate')) ?>
    </div>
    <div class="form-group" style="text-align: center;">
        <input type="hidden" name="perfil" value="2" />
        <?php echo $this->formElement($form->get('btn_save')) ?>
    </div>
<?php echo $this->form()->closeTag() ?>