<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=windows-1254">
</head>
<body>
	<center>
		<h1 style="font: bold 100px Arial, Helvetica, sans-serif;display: block;letter-spacing: -10px;color: #666;margin: 0px;padding: 0px;padding-top: 100px;">Acceso denegado</h1>
	    <h4 style="font: normal 30px Arial, Helvetica, sans-serif;color: #999;margin-bottom: 80px;margin-top: 20px;">No tiene permisos para ingresar a esta URL.</h4>
	    <a href="#" onclick="window.history.go(-1)" style="font: bold 20px Arial, Helvetica, sans-serif;background: #E09101;padding: 10px;color: #FFFFFF;text-decoration: NONE;">Regresar</a>
	</center>
</body>
</html>