<div class="homesliderbg" align="center">
	<div id="container">
		<div id="banner-slide">
	        <!-- start Basic Jquery Slider -->
	        <ul class="bjqs">
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	        </ul>
	        <!-- end Basic jQuery Slider -->
      	</div>
      	<!-- End outer wrapper -->
	</div>
</div>
<div class="categorias" align="center">
	<?php foreach ($categories as $category): ?>
	<div class="categoria" 
			style="background-image: url(<?php echo $this->basePath($category['thumb_img']) ?>);">
		<a href="<?php echo $this->basePath('productsc/' . $category['id']) ?>" class="cat_hover" >
			<?php echo $category['name'] ?>
		</a>
	</div>
	<?php endforeach ?>
</div>