<div class="homesliderbg" align="center">
	<div id="container">
		<div id="banner-slide">
	        <!-- start Basic Jquery Slider -->
	        <ul class="bjqs">
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	        </ul>
	        <!-- end Basic jQuery Slider -->
      	</div>
      	<!-- End outer wrapper -->
	</div>
</div>
<div class="categorias" align="center">
	<h2>Catálogo</h2>
	<div class="categoria" style="background-image: url(<?php echo $this->basePath('images/hogar.jpg') ?>);">
		<a href="hogar.html" class="cat_hover">Hogar</a>
	</div>
	<div class="categoria" style="background-image: url(<?php echo $this->basePath('images/electronica.jpg')?> );">
		<a href="hogar.html" class="cat_hover">Electrónica</a>
	</div>
	<div class="categoria" style="background-image: url(<?php echo $this->basePath('images/relojes.jpg')?>);">
		<a href="hogar.html" class="cat_hover">Relojes</a>
	</div>
</div>