<?php
$title = 'Punto de venta';
$this->headTitle($title);
?>
<?php echo "<br />"; ?>
<div class="index-view view-container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<span class="glyphicon glyphicon-usd"></span> <?= $title; ?>
		</div>
		<div class="panel-body">
			
			<!-- form product -->
			
				<?php
				$form->setAttribute('products', $this->url('products', array('action' => 'add')));
				$form->setAttribute('class', 'form-horizontal');
				$form->setAttribute('enctype', 'multipart/form-data');
				$form->prepare();
	
				echo $this->form()->openTag($form);
				?>
			<div class="row">
				<div class="col-md-6">
					<?php echo $this->formElement($form->get('tipo')) ?>
				
					<?php echo $this->formElement($form->get('client')) ?>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<?php echo $this->formHidden($form->get('sale_id')) ?>
					<table class="table table-bordered">
						<thead>
							<tr>
								<td>Cantidad</td>
								<td>Producto</td>
								<td>precio</td>
								<td>Total</td>
								<td>Acci&oacute;n</td>
							</tr>
						</thead>
  						<tr>
  							<td><?php echo $this->formElement($form->get('cantidad')) ?></td>
  						
  							<td><?php echo $this->formElement($form->get('producto')) ?></td>
  						
  							<td><?php echo $this->formElement($form->get('precio')) ?></td>
  						
  							<td></td>
  							<td></td>
  						
  						</tr>
  			
					</table>
					
				</div>
				
            </div>
            <div class="clearfix"></div>
			<div class="button-set">
				<a href="<?= $this->url('products', array('action'=>'index')); ?>" class="btn btn-danger">
					<span class="glyphicon glyphicon-remove"></span> Cancelar
				</a>
				<button type="submit" id="btn-save" name="submit" class="btn btn-success"><span class="glyphicon glyphicon-floppy-disk"></span> Realizar venta</button>
			</div>
            
            <?php
			echo $this->form()->closeTag();
			?>
		</div>
	</div>
</div>
<script type="text/javascript">

</script>