<div class="homesliderbg" align="center">
	<div id="container">
		<div id="banner-slide">
	        <!-- start Basic Jquery Slider -->
	        <ul class="bjqs">
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	          <li><a href=""><img src="<?php echo $this->basePath('images/slider/home1.png') ?>"></a></li>
	        </ul>
	        <!-- end Basic jQuery Slider -->
      	</div>
      	<!-- End outer wrapper -->
	</div>
</div>