<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('role', 'form');
?>

<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <br />
        <img src="<?php echo $this->basePath(); ?>/images/Login_logo.png" class="img-responsive margin-center" />
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <?php echo $this->form()->openTag($form) ?>
                <div class="form-group">
                    <?php echo $this->formElementErrors($form->get('identity')) ?>
                </div>
                <div class="form-group">
                    <div class="row">
                        <?php $identity = $form->get('identity') ?>
                        <?php $identity->setAttribute('class', 'form-control login-input') ?>
                        <?php $identity->setAttribute('placeholder', 'Usuario') ?>
                        <?php echo $this->formInput($form->get('identity')) ?>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <?php $credential = $form->get('credential') ?>
                        <?php $credential->setAttribute('class', 'form-control login-input') ?>
                        <?php $credential->setAttribute('placeholder', 'Contraseña') ?>
                        <div class="col-md-12"><?php echo $this->formInput($credential) ?></div>
                    </div>
                    <?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>
                </div>
                <div class="form-group">
                    <div class="row"> 
                        <div class="col-md-12 text-center login-check">
                            <input type="checkbox" name="recordar" value="1" /> <span>Recordar mi contraseña</span>
                        </div>
                    </div>                   
                </div>
                <div class="form-group">
                    <div class="row"> 
                        <div class="col-md-12 text-center">
                            <?php $submit = $form->get('submit') ?>
                            <?php $submit->setAttribute('class', 'btn btn-default login-btn') ?>
                            <?php $submit->setLabel('Entrar') ?>
                            <div class="btnEnviar"><?php echo $this->formButton($form->get('submit')) ?></div> 
                        </div>
                    </div>                   
                </div>
                <br />
                <br />
                <div class="form-group">
                    <div class="row"> 
                        <div class="col-md-12 text-center login-registro">
                            <span>¿No estás registrado?</span><br />
                            Solicita tus claves de acceso en Total Mexico
                        </div>
                    </div>                   
                </div>                              
                <?php echo $this->form()->closeTag() ?>
                <br />
            </div>
            <div class="col-md-3"></div>
        </div>
        <br />
        <br />
    </div>
    <div class="col-md-2"></div>
</div>
<script>
//    $(window).load(function() {
//        $(".popup").trigger("click");
//    });
//    $('#myModal').on('hidden.bs.modal', function() {
//        $('#myModal iframe').removeAttr('src');
//    })
</script>


