<h1>Completar Perfil de <?php echo $profile ?></h1>

<?php
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/complete'));
$form->setAttribute('method', 'post')
?>
<?php if($profile_id == 3): ?>
<?php echo $this->form()->openTag($form) ?>
    
    <div class="form-group">
        <?php echo $this->formRow($form->get('razon_social')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('nombre')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('nombre_distribuidor')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('nombre_vendedor')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('domicilio')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('estado')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('cp')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('telefono')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('celular')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('email')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formElement($form->get('btn_save')) ?>
    </div>

<?php echo $this->form()->closeTag() ?>
<?php else: ?>
<?php echo $this->form()->openTag($form) ?>
    
    <div class="form-group">
        <?php echo $this->formRow($form->get('razon_social')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('nombre')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('domicilio')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('estado')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('cp')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('telefono')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('celular')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('email')) ?>
    </div>
    <div class="form-group">
        <?php echo $this->formElement($form->get('btn_save')) ?>
    </div>

<?php echo $this->form()->closeTag() ?>
<?php endif ?>