<?php
	$form = $this->loginForm;
	$form->prepare();
	$form->setAttribute('action', $this->url('zfcuser/login'));
	$form->setAttribute('method', 'post');
	$form->setAttribute('role', 'form');
?>
<div class="narrow">
	<?php echo $this->form()->openTag($form) ?>            
    	<div class="form-group formLoginStyle">
        	<div class="row marginLefRig">
				<div class="col-md-12 formInput errorMsg">
                    <?php echo $this->formElementErrors($form->get('identity')) ?>
				</div>
			</div>
		</div>
    	<div class="form-group formLoginStyle">
        	<div class="row marginLefRig">
				<div class="col-md-12 formInput">
					<?php $identity = $form->get('identity') ?>
                    <?php $identity->setAttribute('class', 'form-control textbox txt-identity') ?>
                    <?php $identity->setAttribute('placeholder', 'Correo electrónico') ?>
                    <?php echo $this->formInput($form->get('identity')) ?>
                </div>
			</div>
		</div>
		<div class="form-group formLoginStyle">
			<div class="row marginLefRig">
				<div class="col-md-12 formInput">
					<?php $credential = $form->get('credential') ?>
                    <?php $credential->setAttribute('class', 'form-control textbox txt-credential') ?>
                    <?php $credential->setAttribute('placeholder', 'Contraseña') ?>
                    <?php echo $this->formInput($credential) ?>
				</div>
 			</div>
		</div>
		<div class="form-group formLoginStyle">
			<div class="row marginLefRig">
				<div class="col-md-12 formInput">
					<?php if ($this->redirect): ?>
                        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                    <?php endif ?>
				</div>
 			</div>
		</div>
        <div class=" text-center">
			<div class="btn-login book">
					<?php $submit = $form->get('submit') ?>
                	<?php $submit->setAttribute('id', 'button_login') ?>
                	<?php $submit->setAttribute('class', 'btn btn-default bLogin') ?>
                    <?php $submit->setLabel('Entrar') ?>
                    <?php echo $this->formButton($form->get('submit')) ?>
			</div>
        </div>
	<?php echo $this->form()->closeTag() ?>
</div>
<!-- <div class="narrow"> -->
<!-- <h2 style="color:#2e2e2e">¿no estas registrado?</h2> -->
<!-- 	<input type="submit" name="button" id="button_login" value="Regístrate"> -->
<!-- </div> -->