<?php 
date_default_timezone_set('America/Mexico_City');
// echo "<pre>";
// var_dump($user_info);

?>
<div class="content">
    <a class="regresar" href="#">Regresar</a>
    <h1>Perfil de usuario</h1>
    <p class="text-header">
        Estos son los datos registrados en el programa, revisa que sean correctos para que tus premios lleguen sin problema.<br />
        Si hay algún dato que quieras modificar envíanos un email a <a href="contacto@brillacontecnolite.com">contacto@brillacontecnolite.com</a> y/o llama al 01-800 228 8940 y con gusto actualizamos tus datos.</p>
    <div class="table_tl" >

    	<table>
    		
    		<tr>
    			<td>&nbsp;</td>
    			<td>&nbsp;</td>
    		</tr>
            <tr>
                <td>Nombre de usuario</td>
                <td><?php echo $username ?></td>
            </tr>
            <tr>
                <td>Nombre completo</td>
                <td><?php echo $user_info->getFullname() ?></td>
            </tr>
            <tr>
                <td>Correo electr&oacute;nico</td>
                <td><?php echo $user_info->getEmail() ?></td>
            </tr>
            <tr>
                <td>Direcci&oacute;n</td>
                <td><?php echo $user_info->getAddress() ?></td>
            </tr>
        	<tr>
                <td>Tel&eacute;fono</td>
                <td><?php echo $user_info->getPhone() ?></td>
            </tr>
            <tr>
                <td>Celular</td>
                <td><?php echo $user_info->getCellphone() ?></td>
            </tr>
			<tr>
                <td>Fecha de nacimiento</td>
                <td><?php echo date('d-m-Y', $user_info->getBirthdate()) ?></td>
            </tr>

        </table>

    </div>


</div>