<br>
<br>
<br>
<br>
<br>
<br>
<div>
    <?php if ($this->send === null): ?>
        <div>
            <h1>Bienvenido</h1>
        </div>
        <div>
            <p>Para recuperar tu contraseña, porfavor introduce tu correo electrónico con el cual fuiste registrado.<br>
                Y en breve recibirás una notificacion mediante correo electrónico con tu información de acceso.</p>
        </div>
    </div>
    <div id="infoUsuarioForm" class="marcoForm">
        <div class="formTitle">
            <h3>Datos de Participante  </h3>
        </div>
        <div>
            <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url('zfcuser/recovery'));
            $form->setAttribute('method', 'post');
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('id', 'recovery');
            echo $this->form()->openTag($form);
            ?>
            <div class="form_element">
                <?php
                $elements = $form->getElements();
                foreach ($elements as $element) :
                    echo '<div class="form-group">';
                    $required = $element->getAttribute('required');
                    echo (null !== $required) ?
                            '<label class="col-sm-3 control-label" for="' . $element->getAttribute('name') . '"><span>* <span>' . $element->getOption('label') . '</label>' : '<label class="col-sm-3 control-label" for="' . $element->getAttribute('name') . '">' . $element->getOption('label') . '</label>';

                    echo '<div class="col-sm-9">' . $this->formElement($element) . '</div>';
                    echo $this->translate($this->formElementErrors($element));
                    echo '</div>';
                    echo '<div class="col-md-11 text-center"><button type="submit" class="btn btn-success" id="enviar">Aceptar</button></div>';
                endforeach;
                echo $this->form()->closeTag($form);
                ?>
            </div>
        </div>
    </div>
<?php elseif ($this->send): ?>
    <h1>Estimado usuario</h1>
    <p>Se ha enviado un correo electrónico a tu bandeja de entrada, en el cual contiene información de acceso </p>
    <button type="submit" onclick="window.location.href = '/user/login'">Regresar</button>
<?php else: ?>
    <h1>Estimado usuario</h1>
    <p>Se ha producido un error al intentar mandar el correo<br>Asegúrate que el correo electrónico proporcionado sea el correcto </p>
    <button type="submit" onclick="window.location.href = '/user/login'">Regresar</button>
<?php endif ?>
<br>
<br>
<br>
<br>
<br>